languageCode = "en-us"
title = "paulgiuliano.com"
baseurl = "https://paulgiuliano.github.io"
theme = "aerial"

[params]
  name = "Paul Giuliano, Ph.D."
  about = "Space engineer &nbsp;&bull;&nbsp; Professor &nbsp;&bull;&nbsp; Media Consultant"
  copyright = "2017 Paul Giuliano"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/heyPaulGiuliano"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/paulgiuliano"

[[params.social]]
  medium = "LastFM"
  icon = "lastfm"
  link = "http://www.last.fm/user/abookofhateYEAH"

#[[params.social]]
#  medium = "Email"
#  icon = "envelope-o"
#  link = "mailto:hey@paulgiuliano.com"

