languageCode = "en-us"
title = "paulgiuliano.com"
baseurl = "https://paulgiuliano.github.io"
theme = "aerial"

[params]
  name = "Paul Giuliano, Ph.D."
  about = "Program manager &nbsp;&bull;&nbsp; Satellite engineer &nbsp;&bull;&nbsp; Astronautics professor &nbsp;&bull;&nbsp; Media consultant"
  copyright = "2020 Paul Giuliano"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/heyPaulGiuliano"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/paulgiuliano"

[[params.social]]
  medium = "Consulting"
  icon = "rocket"
  link = "http://hpspace.co"

[[params.social]]
  medium = "LastFM"
  icon = "lastfm"
  link = "http://www.last.fm/user/abookofhateYEAH"

[[params.social]]
  medium = "GitHub"
  icon = "github"
  link = "https://github.com/paulgiuliano"

#[[params.social]]
#  medium = "Disqus"
#  icon = "question"
#  link = "https://disqus.com/by/paulgiuliano"

#[[params.social]]
#  medium = "Email"
#  icon = "envelope-o"
#  link = "mailto:hey@paulgiuliano.com"
